format = """
$time$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$lua\
$jobs\
$battery\
$status\
$character"""

add_newline = false

[time]
disabled = false
format = '🕙[ $time]($style) '
#time_format = "%a %b %m, %Y %T"
#utc_time_offset = "-5"
#time_range = "10:00:00-14:00:00"

[hostname]
ssh_only = false
format =  "@ [$hostname](bold red) "

[username]
style_user = "#ff00cb bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true

[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[➜](bold red)"

[git_branch]
always_show_remote = true
style = "bold #60b661"
format = "on [$symbol$branch]($style) "

[directory]
truncate_to_repo = false
truncation_length = 8
truncation_symbol = "…/"


